FORMAT: 1A
HOST: https://admin-grupoXX.proyecto2023.unlp.edu.ar

# Documentación API a implementar
Documentación online de la api a realizar en el trabajo integrador de la materia
*Projecto de Software* de la **UNLP**.

## Buscador de Servicios
En esta documentación describiremos los endpoints que creemos que son escenciales
para la implementación correcta de la aplicación.

Estos endpionts serán implementados en la _**aplicación privada**_ que les solicitamos
y consultados/usados desde la _**aplicación pública**_.

::: note
## Nota
Recordá que estos endpoints son los mínimos que nos imaginamos desde la cátedra
como necesarios.

Si dentro del grupo o el doncente asignado consideran que es necesario agregar
algún otro debido a la particularidades de la solución elegida deberán agregarlos.
:::

# Data Structures

## InstitucionData
+ name: `Institución #1` (string) - Nombre de la Institución.
+ information: `Información adicional` (string) - Información de la Institución.
+ address: `Calle 50 N° 1234` (string) - Dirección de la Institución.
+ location: `latitude, longitude` (string) - Nombre de persona a cargo de la misma.
+ web: `www.institucion1.com` (string) - Web de la Institución.
+ `days_and_opening_hours`: `Lunes a viernes de 8 a 18hs` (string) - Días y horarios de atención.
+ email: `info@institution.com` (string) - Información de contacto.
+ enabled: false (boolean) - Habilitado SI o NO.

## InstitucionListData
+ data (array[InstitucionData]) - Lista de intituciones.
+ page: `1` (number) - Número de página actual.
+ `per_page`: `10` (number) - Cantidad de elementos por página.
+ total: `25` (number) - Total de elementos en la lista.

## RequestData
+ title: `a title` (string) - Título de la solicitud.
+ creation_date: `2023-10-10` (string) - Fecha de creación de la solicitud (generada por sistema).
+ close_date: `2023-12-11` (string) - Fecha de finalización de la solicitud (generada por sistema).
+ status: `created` (string) - Estado de la solicitud.
+ description: `a long description` (string) - Descripción de la solicitud.

# RequestListData
+ data (array[RequestData]) - Lista de solicitudes.
+ page: `1` (number) - Número de página actual.
+ per_page: `10` (number) - Cantidad de elementos por página.
+ total: `25` (number) - Total de elementos en la lista.

## ServiceData
+ name: `service name` (string) - Nombre del servicio.
+ description: `a description` (string) - Descripción del servicio.
+ laboratory: `laboratory name` (string) - Nombre del Laboratorio que presta el servicio.
+ keywords: `a list of keywords` (string) - Lista de palabras clave.
+ enabled: false (boolean) - Servicio habilitado SI o NO.

## ServiceListData
+ data (array[ServiceData]) - Lista de servicios.
+ page: `1` (number) - Número de página actual.
+ per_page: `10` (number) - Cantidad de elementos por página.
+ total: `25` (number) - Total de elementos en la lista.

## ServiceTypeData (enum)
+ `Análisis`
+ `Consultoría`
+ `Desarrollo`

## DocTypeData (enum)
+ `DNI`
+ `Libreta Cívica`
+ `Libreta de Enrolamiento`

## GenderData (enum)
+ `Masculino`
+ `Femenino`
+ `Otros (Por favor especifica)`
+ `Prefiero no decir`

## PerfilData
+ user: `usarname` (string) - Nombre de usuario.
+ email: `username@mail.com` (string) - Correco electrónico.
+ document_type (DocTypeData) - Tipo de documento.
+ document_number: `35.555.555` (string) - Número de documento.
+ gender (GenderData) - Género.
+ gender_other: `transgénero` (string) - Género no listado.
+ address: `120 y 50` (string) - Dirección.
+ phone: `221 1212-123` (string) - Teléfono.

# Group Autenticación

## Login [/api/auth]

Se requiere de un token de acceso para acceder a los endpoints con información del usuario registrado.

### Obtener token [POST]

Permite obtener el un JSON Web Token válido para el usuario y password.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Request (application/json)
    + Attributes
        + user: `john.doe@mail.com` (string, required) - User email address
        + password: `QXR0mi38a2` (string, required) - User password

+ Response 200 (application/json)
    + Attributes
        + token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....` (string) - JSON Web Token.
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)
      
# Group Instituciones

## Información de las Instituciones [/api/institutions{?page,per_page}]

### Obtiene todas las Instituciones de la entidad [GET]

Obtiene todas las Instituciones dadas de alta en el sistema.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Parameters
  + page: 2 (integer, optional) - Número de página actual.
        + Default: 1
  + per_page: 10 (integer, optional) - Cantidad de elementos por página.
        + Default: 1

+ Response 200 (application/json)
    + Attributes (InstitucionListData)
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

# Group Perfil

## Información de perfil [/api/me/profile]

### Obtener información del usuario logeado [GET]

Obtiene toda la información del perfil del usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación
+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (PerfilData)
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

# Group Solicitudes de Servicio

## Listado de solicitudes de servicio realizadas por el usuario logueado [/api/me/requests{?page,per_page}]

### Obtiene el listado de solicitudes del usuario logueado [GET]

Obtiene el listado de solicitudes realizadas por el usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Parameters
  + page: 2 (integer, optional) - Número de página actual.
        + Default: 1
  + per_page: 10 (integer, optional) - Cantidad de elementos por página.
        + Default: <config>

+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestListData)
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

## Obtiene la solicitud de servicio [/api/me/requests/{id}]

+ Parameters
    + id: 123 (number, required) - Id de la solicitud de servicio.

### Obtiene la solicitud de servicio [GET]

Obtiene la solicitud realizada por el usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestData)
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

## Carga una solicitud de servicio [/api/me/requests]

### Carga una solicitud de servicio [POST]

Carga una solicitud solicitud de servicio por un usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request (application/json)
    + Attributes
        + title: `a title` (string, required) - Título de la solicitud.
        + description: `a long description` (string, required) - Descripción de la solicitud.

    + Headers

            Authorization: JWT <token>

+ Response 201 (application/json)
    + Attributes
        + id: 123 (number) - Id de la solicitud de servicio.
        + Include RequestData
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

## Carga una nota en la solicitud de servicio [/api/me/requests/{id}/notes]

+ Parameters
    + id: 123 (number) - Id de la solicitud de servicio.

### Carga una nota en la solicitud de servicio [POST]

Carga una nota en la solicitud de servicio por un usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request (application/json)
    + Attributes
        + text: `a long description` (string, required) - Descripción de la solicitud.

    + Headers

            Authorization: JWT <token>

+ Response 201 (application/json)
    + Attributes
        + id: 1 (number, required) - Id de la nota asociada.
        + text: `a long description` (string, required) - Descripción de la solicitud.
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

# Group Servicios

## Buscador de servicios [/api/services/search{?q,type,page,per_page}]

### Obtiene un listado de servicios [GET]

Obtiene un listado de tipos habilitado, filtrado por el criterio de búsqueda.

+ Parameters
  + q (string, required) - El término de búsqueda principal.
  + type (string, optional) - El tipo de búsqueda opcional.
  + page: 2 (integer, optional) - Número de página actual.
        + Default: 1
  + per_page: 10 (integer, optional) - Cantidad de elementos por página.
        + Default: <config>

+ Response 200 (application/json)
    + Attributes (ServiceListData)
    
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

## Obtener servicio [/api/services/{id}]

### Obtiene el detalle del servicio [GET]

Obtiene el detalle del servicio.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Parameters
    + id: 123 - Id del servicio.
    
+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (ServiceData)
            
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)

# Group Tipos de servicios

## Listado de tipos de servicios [/api/services-types]

### Obtiene el listado de tipos de servicios [GET]

Obtiene el listado de tipos de servicios.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes 
        + data (array, fixed-type)
            + `Análisis`
            + `Consultoría`
            + `Desarrollo`

+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)
